import "../styles/styles.scss";
import "../styles/inicio.scss";
import "../styles/detalles.scss";
import "../styles/acercade.scss";
import "../styles/suscribe.scss";
import "../styles/opiniones.scss";
import "../styles/precios.scss";
import "../styles/contactanos.scss";
import "../styles/footer.scss";
